/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wechsljm' at '2/27/17 4:20 PM' with Gradle 2.14.1
 *
 * @author wechsljm, @date 2/27/17 4:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
